version: "3"
services:

   db:
     image: postgres:9.6
     restart: unless-stopped
     environment:
       POSTGRES_PASSWORD: oxefood-noite
       POSTGRES_DB: oxefood-noite
     ports:
       - 5435:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data

